name: Register Schema
on:
  workflow_dispatch:
    inputs:
      magento_version:
        description: 'Magento version'
        required: true
        default: '2.4.6'
      php_version:
        description: 'PHP version'
        required: true
        default: '8.1'

jobs:
  register-schema:
    name: Register Magento 2 GraphQL Schema
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123123q
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker.io/wardenenv/elasticsearch:7.6
        ports:
          - 9200:9200
          - 9300:9300
        env:
          "discovery.type": single-node
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
        options: --health-cmd="rabbitmq-diagnostics check_port_connectivity" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.inputs.php_version }}
          extensions: "bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip, sockets, mcrypt"
          tools: composer:v2
      - name: Create empty composer project
        run: |
          echo ${{ secrets.AUTH_JSON }} >> auth.json
          composer init -n --name reach-digital/register-schema --require magento/product-community-edition:${{ github.event.inputs.magento_version }}
          composer config repositories.magento '{"type": "composer", "url": "https://repo.magento.com/"}'
          composer config --no-plugins allow-plugins.magento/composer-dependency-version-audit-plugin true
          composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
          composer config --no-plugins allow-plugins.magento/magento-composer-installer true
          composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true
          sed -i '$ s/.$//' composer.json
          echo ',"autoload":{"files": ["app/etc/NonComposerComponentRegistration.php"],"psr-0": {"": ["app/code/","generated/code/"]},"psr-4":{"Magento\\":"app/code/Magento/","Magento\\Framework\\": "lib/internal/Magento/Framework/","Magento\\Setup\\": "setup/src/Magento/Setup/", "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"},"psr-0": {"": ["app/code/"]}}}' >> composer.json
          composer install
      - name: Install Magento
        run: |
          php bin/magento setup:install --cleanup-database --backend-frontname=admin --enable-debug-logging=true --amqp-host=localhost --amqp-port=5672 --amqp-user=guest --amqp-password=guest  --db-host=127.0.0.1 --db-name=magento --db-user=root --db-password=123123q --session-save=files --allow-parallel-generation --admin-user=admin --admin-password=Welkom1234 --admin-email=admin@test.com --admin-firstname=Admin --admin-lastname=Admin --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200 --magento-init-params="MAGE_MODE=developer"
          php bin/magento reach-digital:get-graphql-schema
      - name: Publish schema
        run: |
          npm i -g -D @graphql-hive/cli
          hive schema:publish --commit=${{ github.event.inputs.magento_version }} --registry.accessToken ${{secrets.HIVE_ACCESS_TOKEN}} schema.graphql